<script setup lang="ts">
import AppHeader from "~/components/dashboard/AppHeader.vue";
import AppContainer from "~/components/dashboard/AppContainer.vue";
</script>

<template>
  <NuxtLayout>
    <AppContainer>
      <AppHeader/>
      <div class="terms-container">
        <h1>Terms & Conditions</h1>
        <p>
          Welcome to our email summarization tool. By using our service, you agree to the following
          terms and conditions:
        </p>
        <ul>
          <li>You must provide a valid email address to use the service.</li>
          <li>Our tool is designed to help you summarize and prioritize your emails.</li>
          <li>We do not guarantee the accuracy of the summaries generated by our tool.</li>
          <li>We reserve the right to modify or discontinue the service at any time.</li>
          <li>Your use of the service is at your own risk.</li>
        </ul>
        <p>
          For more information, please contact our support team.
        </p>
      </div>
    </AppContainer>
  </NuxtLayout>
</template>

<style scoped>
.terms-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  font-family: Arial, sans-serif;
}

h1 {
  font-size: 2em;
  margin-bottom: 20px;
}

p {
  margin-bottom: 10px;
  line-height: 1.6;
}

ul {
  list-style-type: disc;
  padding-left: 20px;
}

li {
  margin-bottom: 10px;
}
</style>
